---
# tasks file for wordpress
# https://www.digitalocean.com/community/tutorials/how-to-automate-installing-wordpress-on-ubuntu-14-04-using-ansible


- name: Create mysql database
  mysql_db:
    name: "{{ wp_mysql_db }}"
    state: present

- name: Create mysql user
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL'

- name: Download Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  notify: 
    - extract Wordpress

- name: Execute handlers
  meta: flush_handlers

- name: Configuration Vhost
  template: 
    src: vhost_ssl.conf
    dest: /etc/apache2/sites-enabled/vhost_ssl.conf

- name: Copy sample config file
  template: 
    src: wp-config.php
    dest: /var/www/wordpress/wp-config.php
  notify: 
  - restart apache2
  - copy script
