---
# handlers file for wordpress

- name: extract Wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    copy: no

- name: copy script
  template:
    src: wordpress-config.php
    dest: /var/wordpress-config.php
  notify:
    - Execute script
  
- name: Execute script 
  shell: php /var/wordpress-config.php
  notify: 
    - Delete script 

- name: Delete script
  file:
    path: /var/wordpress-config.php
    state: absent

- name: restart apache2
  service:
    name: apache2
    state: restarted
